BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/Process_Deactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to disable various automated processes - validation rules, outbound messages, email alerts, workflows &amp; triggers
    
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1193115680/Process+Deactivation
    
    </description>
    <label>Process Deactivation</label>
</CustomObject>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_All_Triggers__c.field-meta.xml
<fields>
    <fullName>Disable_All_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all triggers (assumes triggers are implemented using our TriggerHandler framework)</description>
    <inlineHelpText>Disable all custom triggers (this excludes triggers provided by managed packages)</inlineHelpText>
    <label>Disable All Triggers</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Benign_Field_Ignore__c.field-meta.xml
<CustomField>
    <fullName>Disable_Benign_Field_Ignore__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the check in the update triggers that means that benign field changes do not run the trigger functionality</description>
    <inlineHelpText>Disable the check in the update triggers that means that benign field changes do not run the trigger functionality</inlineHelpText>
    <label>Disable Benign Field Ignore</label>
    <type>Checkbox</type>
</CustomField>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Email_Alerts__c.field-meta.xml
<fields>
    <fullName>Disable_Email_Alerts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable workflow email alerts (assumes workflow rules check this field)</description>
    <inlineHelpText>Disable workflow email alerts (workflow rules need to be implemented to check this custom setting to have any effect)</inlineHelpText>
    <label>Disable Email Alerts</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Outbound_Messages__c.field-meta.xml
<fields>
    <fullName>Disable_Outbound_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable workflow outbound messages (assumes workflow rules check this field)</description>
    <inlineHelpText>Disable workflow outbound messages (workflow rules need to be implemented to check this custom setting to have any effect)</inlineHelpText>
    <label>Disable Outbound Messages</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Processes__c.field-meta.xml
<fields>
    <fullName>Disable_Processes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all process builders (assumes process builders check this field)</description>
    <inlineHelpText>Disable all process builders (process builders need to be implemented to check this custom setting to have any effect)</inlineHelpText>
    <label>Disable Processes</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Validation_Rules__c.field-meta.xml
<fields>
    <fullName>Disable_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable validation rules (assumes validation rules check this field)</description>
    <inlineHelpText>Disable validation rules (validation rules need to be implemented to check this custom setting to have any effect)</inlineHelpText>
    <label>Disable Validation Rules</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/objects/Process_Deactivation__c/fields/Disable_Workflows__c.field-meta.xml
<fields>
    <fullName>Disable_Workflows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all other workflows (assumes workflow rules check this field)</description>
    <inlineHelpText>Disable all other workflows (workflow rules need to be implemented to check this custom setting to have any effect)</inlineHelpText>
    <label>Disable Workflows</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/core/default/classes/ProcessDeactivationDataFactory.cls
/**
 * Process_Deactivation__c custom setting test data factory
 * 
 * @date    2018-03-09
 * @author  makepositive
 */
@isTest
public class ProcessDeactivationDataFactory extends DataFactory {
    
    public ProcessDeactivationDataFactory() {
        super( 'Process_Deactivation__c' );
    }

    protected override SObject buildDefault() {
        return build();
    }

    /**
     * Build a default Process Deactivation custom setting with all
     * processes enabled.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	sObject - Process_Deactivation__c - All processes enabled
     */
    public Process_Deactivation__c build() {
        return new Process_Deactivation__c(
            SetupOwnerId = UserInfo.getOrganizationId()
        );
    }

    /**
     * Build a Process Deactivation with all processes disabled and insert it
     * 
     * @date    2018-03-04
     * @author  makepositive
     * @return	Process_Deactivation__c - All processes disabled
     */
    public static Process_Deactivation__c deactivateAll() {

        ProcessDeactivationDataFactory factory = new ProcessDeactivationDataFactory();

        Process_Deactivation__c processDeactivationSetting = factory.build();
        processDeactivationSetting.Disable_Validation_Rules__c     = true;
        processDeactivationSetting.Disable_All_Triggers__c         = true;
        processDeactivationSetting.Disable_Processes__c            = true;
        processDeactivationSetting.Disable_Workflows__c            = true;
        processDeactivationSetting.Disable_Benign_Field_Ignore__c  = true;
        processDeactivationSetting.Disable_Email_Alerts__c         = true;
        processDeactivationSetting.Disable_Outbound_Messages__c    = true;

        insert processDeactivationSetting;

        // TODO: If you bring in the trigger handler, then re-instate the following line
        // TriggerHandler.resetProcessDeactivationSetting();

        return processDeactivationSetting;
    }

    /**
     * Remove the passed in process deactivation record
     * 
     * @date    2018-03-04
     * @author  makepositive
     * @param	Process_Deactivation__c - Process_Deactivation__c
     */
    public static void removeDeactivation( Process_Deactivation__c deactivation ) {
        delete deactivation;
        // TODO: If you bring in the trigger handler, then re-instate the following line
        // TriggerHandler.resetProcessDeactivationSetting();
    }
}