BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/HTTP_Response__c.object-meta.xml
<CustomObject>
    <description>Used to store the HTTP callout traffic that is initiated from Salesforce.  In normal operation this should just contain error reporting, though can be switched to log all traffic for debug purposes.
            Documentation on usage can be found here:
            https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1236041904/HTTP+Logging
    </description>
    <label>HTTP Response</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Service_Name__c</columns>
        <columns>Request_Endpoint__c</columns>
        <columns>Request_Method__c</columns>
        <columns>Response_Status_Code__c</columns>
        <columns>Response_Status_Message__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>HTTP Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HTTP Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Request_Body__c.field-meta.xml
<fields>
    <fullName>Request_Body__c</fullName>
    <description>The body of the request that was made (or the first 131,072 characters of it...)</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Request_Endpoint__c.field-meta.xml
<fields>
    <fullName>Request_Endpoint__c</fullName>
    <description>The endpoint that was requested, causing the error</description>
    <label>Request Endpoint</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Request_Method__c.field-meta.xml
<fields>
    <fullName>Request_Method__c</fullName>
    <description>The HTTP method used when making the request</description>
    <label>Request Method</label>
    <length>20</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Response_Body__c.field-meta.xml
<fields>
    <fullName>Response_Body__c</fullName>
    <description>The body of the HTTP response</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Response_Headers__c.field-meta.xml
<fields>
    <fullName>Response_Headers__c</fullName>
    <description>The headers embodied in the response</description>
    <label>Response Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Response_Status_Code__c.field-meta.xml
<fields>
    <fullName>Response_Status_Code__c</fullName>
    <description>The status code embodied in the response</description>
    <label>Response Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Response_Status_Message__c.field-meta.xml
<fields>
    <fullName>Response_Status_Message__c</fullName>
    <description>The status message of the response</description>
    <label>Response Status Message</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/objects/HTTP_Response__c/fields/Service_Name__c.field-meta.xml
<fields>
    <fullName>Service_Name__c</fullName>
    <description>The name of the service that was requested (e.g. SendGrid Send Mail)</description>
    <label>Service_Name</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/Logging_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to control logging levels
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging
    </description>
    <label>Logging Settings</label>
</CustomObject>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_Http_Request_Failure_Logging__c.field-meta.xml
<fields>
    <fullName>Enable_Http_Request_Failure_Logging__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable logging of Failed back-end HTTP Requests? - Is used by the http-logging module, if imported.</description>
    <inlineHelpText>Enable logging of Failed back-end HTTP Requests? - Is used by the http-logging module, if imported.</inlineHelpText>
    <label>Enable logging of Failed HTTP Requests?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_Http_Request_Success_Logging__c.field-meta.xml
<fields>
    <fullName>Enable_Http_Request_Success_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable logging of Successful back-end HTTP Requests? - Is used by the http-logging module, if imported.</description>
    <inlineHelpText>Enable logging of Successful back-end HTTP Requests? - Is used by the http-logging module, if imported.</inlineHelpText>
    <label>Enable logging of Success HTTP Requests?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/http-logging/default/classes/HttpLogger.cls
/**
* System HTTP Request and Response logging Utilities class.
*
* A collection of utility methods for logging HTTP messages to the HTTP Response Log.
*
* Documentation on usage can be found here:
*    https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1236041904/HTTP+Logging
* 
* @date    2019-06-25
* @author  makepositive
*/
public inherited sharing class HttpLogger {

	public class HttpLoggerException extends Exception {}

	/**
	 * Will examine the HTTP Status code and decide if the code represents an error
	 * 
	 * @date    2019-06-25
	 * @author  makepositive
	 * @param   HttpResonse - The response to examine
	 * @return  Boolean - States true if the response contains an error
	 */
	public static Boolean responseHasAnErrorCode( HttpResponse response ) {
		if ( response.getStatusCode() < 200 ) {
			return true;
		}
		return ( response.getStatusCode() >= 300 );
	}

	/**
	 * Log the provided HttpRequest and Response objects into the HTTP_Response object
	 *
	 * Based on custom settings, will either log in all cases (for debugging purposes)
	 * or only when there's an error.
	 * 
	 * @date    2019-06-25
	 * @author  makepositive
	 * @param   String - A reasonably descriptive term for the service that was being requested
	 * @param   HttpRequest - The HTTP request object that was used to make the request
	 * @param   HttpResponse - The HTTP response object that was generated
	 * @return  Id - The Id of the created HTTP_Response object
	 */
	public static Id log( String serviceName, HttpRequest request, HttpResponse response ) {

		Logging_Settings__c logLevels = Logging_Settings__c.getInstance();

        Boolean shouldLog = responseHasAnErrorCode( response ) ? logLevels.Enable_Http_Request_Failure_Logging__c : logLevels.Enable_Http_Request_Success_Logging__c;

		if ( shouldLog ) {

			try {

				HTTP_Response__c log           = new HTTP_Response__c();

				log.Service_Name__c            = serviceName;
	       
				log.Request_Body__c            = request.getBody().abbreviate( 131072 );
				log.Request_Endpoint__c        = request.getEndpoint();
				log.Request_Method__c          = request.getMethod();

				log.Response_Status_Code__c    = response.getStatusCode();
				log.Response_Status_Message__c = response.getStatus();
				log.Response_Body__c           = response.getBody().abbreviate( 131072 );

				String headers = '';
				for( String thisHeaderKey : response.getHeaderKeys() ) {
					headers = headers + thisHeaderKey + ': ' + response.getHeader( thisHeaderKey ) + '\n';
				}

				log.Response_Headers__c        = headers.abbreviate( 32768 );

				insert log;

				return log.Id;

			} catch ( Exception e ) {
				throw new HttpLoggerException( 'Unable to log the HTTP response.' );
			}
		}

		return null;
	}
}