BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/Logging_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to control logging levels
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging
    </description>
    <label>Logging Settings</label>
</CustomObject>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Error_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Error_Messages__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable logging of error level messages?</description>
    <inlineHelpText>Enable logging of error level messages?</inlineHelpText>
    <label>Enable System Log Error Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Info_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Info_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable logging of info level messages?</description>
    <inlineHelpText>Enable logging of info level messages?</inlineHelpText>
    <label>Enable System Log Info Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Warning_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Warning_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable logging of warning level messages?</description>
    <inlineHelpText>Enable logging of warning level messages?</inlineHelpText>
    <label>Enable System Log Warning Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>Logging object to store messages generated by Apex or Integrations.
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging    
    </description>
    <label>System Log</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <listViews>
        <fullName>Apex</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Source__c</field>
            <operation>equals</operation>
            <value>Apex</value>
        </filters>
        <label>Apex</label>
    </listViews>
    <listViews>
        <fullName>Errors</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Error</value>
        </filters>
        <label>Errors</label>
    </listViews>
    <listViews>
        <fullName>Info</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Info</value>
        </filters>
        <label>Info</label>
    </listViews>
    <listViews>
        <fullName>Integration</fullName>
        <columns>NAME</columns>
        <columns>Level__c</columns>
        <columns>Reference__c</columns>
        <columns>Message__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Source__c</field>
            <operation>equals</operation>
            <value>Integration</value>
        </filters>
        <label>Integration</label>
    </listViews>
    <listViews>
        <fullName>Warning</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Warning</value>
        </filters>
        <label>Warning</label>
    </listViews>
    <nameField>
        <displayFormat>SL-{00000000}</displayFormat>
        <label>System Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Class__c.field-meta.xml
<fields>
    <fullName>Class__c</fullName>
    <description>Source Apex class</description>
    <inlineHelpText>Source Apex class</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Level__c.field-meta.xml
<fields>
    <fullName>Level__c</fullName>
    <description>Message level</description>
    <inlineHelpText>Message level</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Message__c.field-meta.xml
<fields>
    <fullName>Message__c</fullName>
    <description>Full message details</description>
    <inlineHelpText>Full message details</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Method__c.field-meta.xml
<fields>
    <fullName>Method__c</fullName>
    <description>Source Apex method</description>
    <inlineHelpText>Source Apex method</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Reference__c.field-meta.xml
<fields>
    <fullName>Reference__c</fullName>
    <description>Error identifier</description>
    <inlineHelpText>Error identifier</inlineHelpText>
    <label>Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Related_Record_Id__c.field-meta.xml
<fields>
    <fullName>Related_Record_Id__c</fullName>
    <description>Id of record related to message</description>
    <inlineHelpText>Id of record related to message</inlineHelpText>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Source__c.field-meta.xml
<fields>
    <fullName>Source__c</fullName>
    <description>Source of message</description>
    <inlineHelpText>Source of message</inlineHelpText>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Stack_Trace__c.field-meta.xml
<fields>
    <fullName>Stack_Trace__c</fullName>
    <description>Apex stack trace</description>
    <inlineHelpText>Apex stack trace</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/logging/default/classes/LogUtils.cls
/**
* System Logging Utilities class.
*
* A collection of utility methods for logging messages to the System Log.
*
* Documentation on usage can be found here:
*    https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging
* 
* @date    2018-03-09
* @author  makepositive
*/
public inherited sharing class LogUtils {
    
    /**
     * Name of log source for Apex.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	String - System log source - Apex
     */
    public static final String LOG_SOURCE_APEX = 'Apex';
    
    /**
     * Logging levels - must match the Level__c picklist values.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	Level - Info / Warning / Error
     */
    public enum Level { Info, Warning, Error }
    
    /**
     * Get current logging settings - if not present default to logging
     * Errors only.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	Logging_Settings__c - Logging custom setting
     */
    private static Logging_Settings__c loggingSettings {
        get {
            if (loggingSettings == null) {
                loggingSettings = Logging_Settings__c.getInstance();
        		
                if (loggingSettings.Name == null) {
                    loggingSettings = new Logging_Settings__c(
                        Enable_System_Log_Error_Messages__c = true,
                        Enable_System_Log_Warning_Messages__c = false,
                        Enable_System_Log_Info_Messages__c = false
                    );
                }
            }
            return loggingSettings;
        }
        set;
    }
    
    /**
     * Log message to system log
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	Level - Logging level (Info, Warning, Error)
     * @param	String - Log reference/identifier
     * @param	String - Full message text
     * @param	Id - Optional Id of related record
     * @return	System_Log__c - Inserted System Log entry
     */
    public static System_Log__c log(Level level, String reference, String message, Id relatedRecordId) {
        return insertLog(level, reference, message, relatedRecordId, true);
    }

    /**
     * Log message to system log
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	Level - Logging level (Info, Warning, Error)
     * @param	String - Log reference/identifier
     * @param	String - Full message text
     * @param	Id - Optional Id of related record
     * @return	System_Log__c - Inserted System Log entry
     */
    public static System_Log__c log(Level level, String reference, String message, Id relatedRecordId, Boolean doDML) {
       return insertLog(level, reference, message, relatedRecordId, doDML);
    }

    /**
     * Log message to system log from DmlException
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	String - Log reference/identifier
     * @param	DmlException - Source DmlException
     * @return	System_Log__c - Inserted System Log entry
     */
    public static System_Log__c log(String reference, DmlException ex) {
        return insertLog(Level.Error, reference, ex.getMessage(), ex.getDmlId(0), true);
    }

    /**
     * Log message to system log from Exception
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	String - Log reference/identifier
     * @param	DmlException - Source Exception
     * @return	System_Log__c - Inserted System Log entry
     */
    public static System_Log__c log(String reference, Exception ex) {
        return insertLog(Level.Error, reference, ex.getMessage(), null, true);
    }

    /**
     * Internal method for logging message to system log
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	Level - Logging level (Info, Warning, Error)
     * @param	String - Log reference/identifier
     * @param	String - Full message text
     * @param	Id - Optional Id of related record
     * @return	System_Log__c - Inserted System Log entry
     */
    private static System_Log__c insertLog(Level level, String reference, String message, Id relatedRecordId, Boolean doDML) {        
        System_Log__c log = new System_Log__c(
            Level__c             = level.name(),
			Reference__c         = reference,
            Message__c           = message,
            Class__c             = StackTraceUtils.getClassName(2),
            Method__c            = StackTraceUtils.getMethod(2),
            Stack_Trace__c       = StackTraceUtils.getStackTrace(2),
            Related_Record_Id__c = relatedRecordId,
            Source__c            = LOG_SOURCE_APEX
        );
        
        Boolean enableLogging = 
               (level == LogUtils.Level.Error && loggingSettings.Enable_System_Log_Error_Messages__c)
            || (level == LogUtils.Level.Warning && loggingSettings.Enable_System_Log_Warning_Messages__c)
            || (level == LogUtils.Level.Info && loggingSettings.Enable_System_Log_Info_Messages__c);
        
        if (enableLogging && doDML) {
            insert log;
        }
        
        return log;
    }
}