BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/Logging_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to control logging levels
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging
    </description>
    <label>Logging Settings</label>
</CustomObject>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Error_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Error_Messages__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable logging of error level messages?</description>
    <inlineHelpText>Enable logging of error level messages?</inlineHelpText>
    <label>Enable System Log Error Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Info_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Info_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable logging of info level messages?</description>
    <inlineHelpText>Enable logging of info level messages?</inlineHelpText>
    <label>Enable System Log Info Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/Logging_Settings__c/fields/Enable_System_Log_Warning_Messages__c.field-meta.xml
<fields>
    <fullName>Enable_System_Log_Warning_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable logging of warning level messages?</description>
    <inlineHelpText>Enable logging of warning level messages?</inlineHelpText>
    <label>Enable System Log Warning Messages?</label>
    <type>Checkbox</type>
</fields>

BoilerPlateOrg/force-app/logging/default/classes/LoggingSettingsDataFactory.cls
/**
 * Logging_Settings__c custom setting test data factory
 * 
 * @date    2018-03-09
 * @author  makepositive
 */
@isTest
public class LoggingSettingsDataFactory extends DataFactory {
    
    public LoggingSettingsDataFactory() {
        super( 'Logging_Settings__c' );
    }

    protected override SObject buildDefault() {
        return build();
    }

    /**
     * Build a default Logging Settings custom setting with all
     * logging enabled.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	sObject - Logging_Settings__c - All logging enabled
     */
    public Logging_Settings__c build() {
        return build(true, true, true);
    }
    /**
     * Build a Logging Settings custom setting.
     * 
     * @date    2018-03-097
     * @author  makepositive
     * @param	Boolean - Enable error logging?
     * @param	Boolean - Enable warning logging?
     * @param	Boolean - Enable info logging?
     * @return	sObject - Logging_Settings__c
     */
	public Logging_Settings__c build(final Boolean errorLogging, final Boolean warningLogging, final Boolean infoLogging) {
        return new Logging_Settings__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
        	Enable_System_Log_Error_Messages__c = errorLogging, 
            Enable_System_Log_Warning_Messages__c = warningLogging,
            Enable_System_Log_Info_Messages__c = infoLogging
        );
    }
}