BoilerPlateOrg/force-app/core/default/objects/Application_Properties__c/Application_Properties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Allows the optional configuration of settings specific to this implementation of Salesforce.
    Documentation should be produced for the settings that can be created to customise the behaviour of the application.
    
    Note: This custom setting requires that 'Manage List Custom Settings Type' is enabled under Setup->Data->Schema Settings.
    
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1193115688/Application+Properties
    
    </description>
    <label>Application Properties</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Value__c</columns>
        <columns>Description__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
</CustomObject>

BoilerPlateOrg/force-app/core/default/objects/Application_Properties__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Application Property value, stored as a string but can be retrieved in code as a string, boolean or integer. Boolean properties should have a value of &apos;true&apos; or &apos;false&apos;.</description>
    <inlineHelpText>Application Property value, stored as a string but can be retrieved in code as a string, boolean or integer. Boolean properties should have a value of &apos;true&apos; or &apos;false&apos;.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BoilerPlateOrg/force-app/core/default/classes/ApplicationPropertyDataFactory.cls
/**
 * Application_Properties__c custom setting test data factory
 * 
 * @date    2018-03-09
 * @author  makepositive
 */
@isTest
public class ApplicationPropertyDataFactory extends DataFactory {

    public ApplicationPropertyDataFactory() {
        super( 'Application_Properties__c' );
    }

    protected override SObject buildDefault() {
        return build();
    }

    /**
     * Build a default Application Property
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @return	sObject - Application_Properties__c - NAME / VALUE
     */
    public Application_Properties__c build() {
        return build('NAME', 'VALUE');
    }
    
    /**
     * Build an Application Property
     * 
     * @date    2018-03-097
     * @author  makepositive
     * @param	String - Name of application property
     * @param	String - Value of application property
     * @return	sObject - Application_Properties__c
     */
	public Application_Properties__c build(final String name, final String value) {
        return new Application_Properties__c(
        	Name = name, 
            Value__c = value
        );
    }
}