BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>Logging object to store messages generated by Apex or Integrations.
    Documentation on usage can be found here:
        https://makepositive.atlassian.net/wiki/spaces/DEV/pages/1195180104/Logging    
    </description>
    <label>System Log</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <listViews>
        <fullName>Apex</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Source__c</field>
            <operation>equals</operation>
            <value>Apex</value>
        </filters>
        <label>Apex</label>
    </listViews>
    <listViews>
        <fullName>Errors</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Error</value>
        </filters>
        <label>Errors</label>
    </listViews>
    <listViews>
        <fullName>Info</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Info</value>
        </filters>
        <label>Info</label>
    </listViews>
    <listViews>
        <fullName>Integration</fullName>
        <columns>NAME</columns>
        <columns>Level__c</columns>
        <columns>Reference__c</columns>
        <columns>Message__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Source__c</field>
            <operation>equals</operation>
            <value>Integration</value>
        </filters>
        <label>Integration</label>
    </listViews>
    <listViews>
        <fullName>Warning</fullName>
        <columns>NAME</columns>
        <columns>Source__c</columns>
        <columns>Level__c</columns>
        <columns>Message__c</columns>
        <columns>Class__c</columns>
        <columns>Method__c</columns>
        <columns>Related_Record_Id__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Level__c</field>
            <operation>equals</operation>
            <value>Warning</value>
        </filters>
        <label>Warning</label>
    </listViews>
    <nameField>
        <displayFormat>SL-{00000000}</displayFormat>
        <label>System Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Class__c.field-meta.xml
<fields>
    <fullName>Class__c</fullName>
    <description>Source Apex class</description>
    <inlineHelpText>Source Apex class</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Level__c.field-meta.xml
<fields>
    <fullName>Level__c</fullName>
    <description>Message level</description>
    <inlineHelpText>Message level</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Message__c.field-meta.xml
<fields>
    <fullName>Message__c</fullName>
    <description>Full message details</description>
    <inlineHelpText>Full message details</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Method__c.field-meta.xml
<fields>
    <fullName>Method__c</fullName>
    <description>Source Apex method</description>
    <inlineHelpText>Source Apex method</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Reference__c.field-meta.xml
<fields>
    <fullName>Reference__c</fullName>
    <description>Error identifier</description>
    <inlineHelpText>Error identifier</inlineHelpText>
    <label>Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Related_Record_Id__c.field-meta.xml
<fields>
    <fullName>Related_Record_Id__c</fullName>
    <description>Id of record related to message</description>
    <inlineHelpText>Id of record related to message</inlineHelpText>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Source__c.field-meta.xml
<fields>
    <fullName>Source__c</fullName>
    <description>Source of message</description>
    <inlineHelpText>Source of message</inlineHelpText>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</fields>

BoilerPlateOrg/force-app/logging/default/objects/System_Log__c/fields/Stack_Trace__c.field-meta.xml
<fields>
    <fullName>Stack_Trace__c</fullName>
    <description>Apex stack trace</description>
    <inlineHelpText>Apex stack trace</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</fields>

BoilerPlateOrg/force-app/logging/default/classes/LogUtilsTest.cls
/**
 * Test class for System Logging Utilities class.
 *
 * @date    2018-03-09
 * @author  makepositive
 */
@isTest
public class LogUtilsTest {
    
    private static final Id EXAMPLE_ID = TestUtils.generateId( 'Contact' );

    /**
	 * @method 	log
	 * @case   	Insert info log entry with logging enabled
	 * @result 	A valid system log entry
	 */
    @isTest static void logUtils_log_params_infoLoggingEnabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(false, false, true)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Info, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        verifySystemLog('Info', 'Test Reference', 'Test String', EXAMPLE_ID, 'logUtils_log_params_infoLoggingEnabled');
    }

    /**
	 * @method 	log
	 * @case   	Insert info log entry with logging disabled
	 * @result 	No system log entry
	 */
    @isTest static void logUtils_log_params_infoLoggingDisabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(true, true, false)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Info, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        system.assertEquals(0, [SELECT COUNT() FROM System_Log__c], 'Logging disabled, should be no log entry');
    }

    /**
	 * @method 	log
	 * @case   	Insert warning log entry with logging enabled
	 * @result 	A valid system log entry
	 */
    @isTest static void logUtils_log_params_warningLoggingEnabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(false, true, false)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Warning, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        verifySystemLog('Warning', 'Test Reference', 'Test String', EXAMPLE_ID, 'logUtils_log_params_warningLoggingEnabled');
    }

    /**
	 * @method 	log
	 * @case   	Insert warning log entry with logging disabled
	 * @result 	No system log entry
	 */
    @isTest static void logUtils_log_params_warningLoggingDisabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(true, false, true)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Warning, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        system.assertEquals(0, [SELECT Count() FROM System_Log__c], 'Logging disabled, should be no log entry');
    }
    
    /**
	 * @method 	log
	 * @case   	Insert error log entry with logging enabled
	 * @result 	A valid system log entry
	 */
    @isTest static void logUtils_log_params_errorLoggingEnabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(true, false, false)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Error, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        verifySystemLog('Error', 'Test Reference', 'Test String', EXAMPLE_ID, 'logUtils_log_params_errorLoggingEnabled');
    }

    /**
	 * @method 	log
	 * @case   	Insert error log entry with logging disabled
	 * @result 	No system log entry
	 */
    @isTest static void logUtils_log_params_errorLoggingDisabled() {
        LoggingSettingsDataFactory loggingSettingsFactory = new LoggingSettingsDataFactory();
        
        loggingSettingsFactory.create(
            loggingSettingsFactory.build(false, true, true)
        );
        
        Test.startTest();
            LogUtils.log(LogUtils.Level.Error, 'Test Reference', 'Test String', EXAMPLE_ID );
        Test.stopTest();
        
        system.assertEquals(0, [SELECT Count() FROM System_Log__c], 'Logging disabled, should be no log entry');
    }

    /**
	 * @method 	log
	 * @case   	Insert error log entry from an exception with default logging settings
	 * @result 	A valid system log entry
	 */
    @isTest static void logUtils_log_exception_defaultSettings() {
        Test.startTest();
        try {
            throw new TestException('Test Exception');
        } catch (TestException ex) {
            LogUtils.log('Test Reference', ex);
        }
        Test.stopTest();
        
        verifySystemLog('Error', 'Test Reference', 'Test Exception', null, 'logUtils_log_exception_defaultSettings');
    }

    /**
	 * @method 	log
	 * @case   	Insert error log entry from a dml exception with default logging settings
	 * @result 	A valid system log entry
	 */
    @isTest static void logUtils_log_dmlException_defaultSettings() {        
        Test.startTest();
        try {
            insert new Account();
        } catch (DmlException ex) {
            LogUtils.log('Test Reference', ex);
        }
        Test.stopTest();
        
        verifySystemLog('Error', 'Test Reference', 'REQUIRED_FIELD_MISSING', null, 'logUtils_log_dmlException_defaultSettings');
    }

    /**
     * Verify saved system log entry.
     * 
     * @date    2018-03-09
     * @author  makepositive
     * @param	String - Expected log entry level
     * @param	String - Expected log entry reference
     * @param	String - Expected log entry message
     * @param	String - Expected log entry record id
     * @param	String - Expected log entry method name
     */
    static void verifySystemLog(String expectedLevel, String expectedReference, String expectedMessage, String expectedId, String expectedMethod) {
        System_Log__c log = [SELECT Id, Level__c, Reference__c, Message__c, Class__c, Method__c, 
                             	Stack_Trace__c, Related_Record_Id__c, Source__c 
                             FROM System_Log__c
                             LIMIT 1][0];
        
        System.assertEquals(expectedLevel, log.Level__c, 'Level not set correctly');
        System.assertEquals(expectedReference, log.Reference__c, 'Reference not set correctly');
        System.assert(log.Message__c.contains(expectedMessage), 'Message not set correctly');
        System.assertEquals(expectedId, log.Related_Record_Id__c, 'Related Record not set correctly');
        System.assertEquals('LogUtilsTest', log.Class__c, 'Class not set correctly');
        System.assertEquals(expectedMethod, log.Method__c, 'Method not set correctly');
        System.assertEquals('Apex', log.Source__c, 'Source not set correctly');
        System.assert(log.Stack_Trace__c.contains('LogUtilsTest'), 'Stack trace should contain class');
        System.assert(log.Stack_Trace__c.contains(expectedMethod), 'Stack trace should contain method');
    }

    /**
     * Test Exception to check exception logging.
     * 
     * @date    2018-03-09
     * @author  makepositive
     */
    public class TestException extends Exception {}
}